pull_request_rules:
  - name: Automatically backport to 3.16.x based on label
    conditions:
      - base=main
      - label=backport-3.16.x
      - label!=backport-3.15.x
    actions:
      backport:
        branches:
          - 3.15.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to 3.16.x & 3.15.x based on label
    conditions:
      - base=main
      - label=backport-3.16.x
      - label=backport-3.15.x
    actions:
      backport:
        branches:
          - 3.15.x
        labels:
          - backport-3.15.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to 3.15.x based on label
    conditions:
      - base=3.16.x
      - label=backport-3.15.x
    actions:
      backport:
        branches:
          - 3.15.x
        assignees:
          - "{{ author }}"
