name: Test
on:
  push:
    branches:
      - main
      - bump-rbe
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
        - "23.3"
        - "24.3"
        - "25.0"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
    - name: TEST
      working-directory: test
      run: |
        ERLANG_HOME="$(dirname $(dirname $(which erl)))"
        bazelisk test //... \
          --noexperimental_enable_bzlmod \
          --color=yes
    - name: RESOVLE TEST LOGS PATH
      working-directory: test
      run: |
        echo "::set-output name=LOGS_PATH::$(readlink -f bazel-testlogs)"
      id: resolve-test-logs-path
    - name: CAPTURE TEST LOGS
      uses: actions/upload-artifact@v2
      with:
        name: bazel-testlogs-${{matrix.otp}}
        path: ${{ steps.resolve-test-logs-path.outputs.LOGS_PATH }}/*
  test-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
        - "23.3"
        - "24.3"
        - "25.0"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
    - name: CONFIGURE BAZEL
      id: configure
      working-directory: test
      shell: bash
      run: |
        cat << EOF >> user.bazelrc
          startup --windows_enable_symlinks
          build --enable_runfiles
        EOF

        ERL_PATH="$(which erl)"
        ERLANG_HOME="${ERL_PATH/\/bin\/erl/}"
        echo "::set-output name=ERLANG_HOME::${ERLANG_HOME}"
    - name: TEST
      working-directory: test
      run: |
        set "ERLANG_HOME=${{ steps.configure.outputs.ERLANG_HOME }}"

        bazelisk test //... --noexperimental_enable_bzlmod
    #! https://github.com/actions/upload-artifact/issues/240
    #! - name: RESOVLE TEST LOGS PATH
    #!   run: |
    #!     Set-Variable -Name logs_path -Value (Get-Item bazel-testlogs).Target
    #!     Write-Output "::set-output name=LOGS_PATH::$logs_path"
    #!   id: resolve-test-logs-path
    #! - name: CAPTURE TEST LOGS
    #!   uses: actions/upload-artifact@v2
    #!   with:
    #!     name: bazel-testlogs-${{matrix.otp}}
    #!     path: ${{ steps.resolve-test-logs-path.outputs.LOGS_PATH }}
  test-bzlmod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
        - "23.3"
        - "24.3"
        - "25.0"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
    - name: CONFIGURE BAZEL
      working-directory: test
      run: |
        cat << EOF >> user.bazelrc
          build:buildbuddy --remote_download_minimal
          build:buildbuddy --color=yes
        EOF
    - name: TEST
      working-directory: test
      run: |
        ERLANG_HOME="$(dirname $(dirname $(which erl)))"
        bazelisk test //...
    - name: RESOVLE TEST LOGS PATH
      working-directory: test
      run: |
        echo "::set-output name=LOGS_PATH::$(readlink -f bazel-testlogs)"
      id: resolve-test-logs-path
    - name: CAPTURE TEST LOGS
      uses: actions/upload-artifact@v2
      with:
        name: bazel-testlogs-bzlmod-${{matrix.otp}}
        path: ${{ steps.resolve-test-logs-path.outputs.LOGS_PATH }}/*
  test-bzlmod-internal-erlang:
    runs-on: ubuntu-latest
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE BAZEL
      working-directory: test
      run: |
        cat << EOF >> user.bazelrc
          build:buildbuddy --remote_download_minimal
          build:buildbuddy --color=yes

          #! build:rbe --extra_execution_platforms=@erlang_config//:erlang_24_platform
        EOF
    - name: BUILD
      working-directory: test
      run: |
        bazelisk build @rules_erlang//tools:erlang_headers \
          --config=rbe \
          --toolchain_resolution_debug="@rules_erlang.*" \
          --verbose_failures
    - name: TEST
      working-directory: test
      run: |
        bazelisk test //... \
          --config=rbe \
          --toolchain_resolution_debug="@rules_erlang.*" \
          --verbose_failures
    - name: RESOVLE TEST LOGS PATH
      working-directory: test
      run: |
        echo "::set-output name=LOGS_PATH::$(readlink -f bazel-testlogs)"
      id: resolve-test-logs-path
    - name: CAPTURE TEST LOGS
      uses: actions/upload-artifact@v2
      with:
        name: bazel-testlogs-bzlmod-${{matrix.otp}}
        path: ${{ steps.resolve-test-logs-path.outputs.LOGS_PATH }}/*
